name: Tests - PyDev

on: [push, pull_request]
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'
          
      - name: Installed Maven version
        run:  echo "version=$(mvn -q -v)" >> $GITHUB_OUTPUT
        shell: bash
        
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.5
          
      - name: New Maven version
        run:  echo "version=$(mvn -q -v)" >> $GITHUB_OUTPUT
        shell: bash
          
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.12
          
      - name: Set up Python 3.8 deps
        run: |
            python3 -m pip install PyQt5 cython numpy django zope.interface

      - name: Print Python/Java info
        run: |
            echo ---- 
            echo ----
            which python3
            python3 -c "import numpy;print(numpy.__version__, numpy.__file__)"
            python3 -c "import django;print(django.__file__)"
            python3 -c "import hmac;print(hmac.__file__)"
            echo SKIPPED python3 -c "import PyQt5;print(PyQt5.__file__)"
            python3 plugins/org.python.pydev.core/pysrc/interpreterInfo.py
            
            echo ---- 
            echo ----
            which java
            which mvn
            echo ---- rt.jar should be listed below
            find /opt/hostedtoolcache/Java_Adopt_jdk/17.0.9-9/x64/ -name "*.jar"
            
      - name: xvfb
        shell: bash
        env:
          DISPLAY: ":99.0"
        run: |
          sudo apt install libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0
          /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1200x24 -ac +extension GLX

        
      - name: Build with Maven
        run: mvn install -DskipTests=true

      - name: Add tests to plugin
        run: python3 builders/org.python.pydev.build/add_tests_to_plugins.py
        
      - name: Test with Maven
        env: 
            # We set the PYDEV_TEST_PLATFORM to control which TestDependent we use (i.e. TestDependent.github.properties)
            PYDEV_TEST_PLATFORM: github
            DISPLAY: ":99.0"
        run: mvn integration-test --batch-mode